#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json
test_format = 1.0


[default]
	
	args.phpboost_pwd = "My_Super_PWD_for_PHPBoost"
	args.phpboost_admin = "Admin"
	
	[default.curl_tests]
	#install.expect_title = "Installation de PHPBoost - Préambule"
	install.expect_return_code = 200
