#!/bin/bash


source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

ynh_app_setting_set --key=php_upload_max_filesize --value=256M
ynh_app_setting_set --key=php_post_max_size --value=256M

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir"

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Configuring NGINX web server..."

# Create a dedicated NGINX config
ynh_config_add_nginx

# Create a dedicated PHP-FPM config
ynh_config_add_phpfpm

#Execute Installation
ynh_script_progression "Installing $app ..."

#(use the template file "conf/config.php" from the app's package)
ynh_config_add --template="config.php" --destination="$install_dir/kernel/db/config.php" 

#Populate DATABASE with "Fake" SQL
ynh_script_progression "Populate DATABASE $db_name with Fake SQL ..."
mysql --binary-mode 1
ynh_mysql_db_shell < ../conf/phpboost_blank_install.sql

ynh_script_progression "RUN the real instalation of $app ..."
ynh_exec_as_app cd $install_dir
ynh_exec_as_app  php phpboost install --db-pwd $db_pwd --db-user $db_user --ws-server $domain --ws-path $path --u-login $phpboost_admin --u-pwd $phpboost_pwd
ynh_safe_rm $install_dir/install

# Tweek APPCI test
#if [ ynh_in_ci_tests ]; then
#ynh_script_progression "Tweek APP CI tests ..."
#	mv $install_dir/install $install_dir/install-old
#	mkdir $install_dir/install
#	echo "<?php echo 'Hello World'; ?>" > $install_dir/install/index.php
#fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
